version: "2"
services:
  JiraService:
    build: ./nodeJira
    image: cstjira
    ports:
      - "5000:5000"

  sqs:
    image: graze/sqs-local
    ports:
      - 9324:9324
    volumes:
      - ./sqs/queue.conf:/elasticmq.conf
 
